package com.hibernate.zoologico.pojo;
// Generated 2 Dec 2022, 13:40:42 by Hibernate Tools 5.5.9.Final

import java.math.BigDecimal;

/**
 * Animales generated by hbm2java
 */
public class Animales implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String habitat;
	private BigDecimal pesoAproximado;

	public Animales() {
	}

	public Animales(String nombre, String habitat, BigDecimal pesoAproximado) {
		this.nombre = nombre;
		this.habitat = habitat;
		this.pesoAproximado = pesoAproximado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getHabitat() {
		return this.habitat;
	}

	public void setHabitat(String habitat) {
		this.habitat = habitat;
	}

	public BigDecimal getPesoAproximado() {
		return this.pesoAproximado;
	}

	public void setPesoAproximado(BigDecimal pesoAproximado) {
		this.pesoAproximado = pesoAproximado;
	}

}
