package pojo;
// Generated 25 Nov 2022, 12:11:07 by Hibernate Tools 5.5.9.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Animales generated by hbm2java
 */
@Entity
@Table(name = "animales")
public class Animal implements java.io.Serializable {

	@Id //Esto es para decir que esta variable interna es un id
	@Column(name = "id") //Esto es para decir que pertenece a la columna id
	@GeneratedValue(strategy = GenerationType.IDENTITY) //Esto es decir que el id es autoincrementable
	private Integer id;
	
	@Column(name = "nombre", unique = true, nullable = false, length = 40) //Aqui, ademas de decir a qué columna pertenece, le decimos que es unico, que es un campo obligatorio y que tiene una longitud de 40 caracteres
	private String nombre;
	
	@Column(name = "habitat", nullable = false, length = 40)
	private String habitat;
	
	@Column(name = "peso_aproximado", nullable = false, length = 10, precision = 2)
	private BigDecimal pesoAproximado;

	public Animal() {
	}

	public Animal(String nombre, String habitat, BigDecimal pesoAproximado) {
		this.nombre = nombre;
		this.habitat = habitat;
		this.pesoAproximado = pesoAproximado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getHabitat() {
		return this.habitat;
	}

	public void setHabitat(String habitat) {
		this.habitat = habitat;
	}

	public BigDecimal getPesoAproximado() {
		return this.pesoAproximado;
	}

	public void setPesoAproximado(BigDecimal pesoAproximado) {
		this.pesoAproximado = pesoAproximado;
	}

}
