package pojo;
// Generated 2 Dec 2022, 14:08:31 by Hibernate Tools 5.5.9.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Zoologicos generated by hbm2java
 */
@Entity
@Table(name = "zoologicos")
public class Zoologicos implements java.io.Serializable {

	@Id //Esto es para decir que esta variable interna es un id
	@Column(name = "id") //Esto es para decir que pertenece a la columna id
	@GeneratedValue(strategy = GenerationType.IDENTITY) //Esto es decir que el id es autoincrementable
	private int id;
	@Column(name = "nombre", unique = true, nullable = false, length = 40) 
	private String nombre;
	@Column(name = "ciudad", unique = true, nullable = false, length = 40)
	private String ciudad;
	@Column(name = "anio_fundacion", nullable = false)
	private int anioFundacion;

	public Zoologicos() {
	}

	public Zoologicos(String nombre, String ciudad, int anioFundacion) {
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.anioFundacion = anioFundacion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public int getAnioFundacion() {
		return this.anioFundacion;
	}

	public void setAnioFundacion(int anioFundacion) {
		this.anioFundacion = anioFundacion;
	}

}
