package pojo;
// Generated 25 Nov 2022, 14:02:57 by Hibernate Tools 5.5.9.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Series generated by hbm2java
 */
@Entity
@Table(name = "series")
public class Serie implements java.io.Serializable {

	@Id //Esto es para decir que esta variable interna es un id
	@Column(name = "id") //Esto es para decir que pertenece a la columna id
	@GeneratedValue(strategy = GenerationType.IDENTITY) //Esto es decir que el id es autoincrementable
	private Integer id;
	
	@Column(name = "titulo", unique = true, nullable = false, length = 100)
	private String titulo;
	
	@Column(name = "edad", unique = true, nullable = false)
	private Integer edad;
	
	@Column(name = "plataforma", unique = true, nullable = false, length = 40)
	private String plataforma;
	
	private Set temporadases = new HashSet(0);

	public Serie() {
	}

	public Serie(String titulo) {
		this.titulo = titulo;
	}

	public Serie(String titulo, Integer edad, String plataforma, Set temporadases) {
		this.titulo = titulo;
		this.edad = edad;
		this.plataforma = plataforma;
		this.temporadases = temporadases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public String getPlataforma() {
		return this.plataforma;
	}

	public void setPlataforma(String plataforma) {
		this.plataforma = plataforma;
	}

	public Set getTemporadases() {
		return this.temporadases;
	}

	public void setTemporadases(Set temporadases) {
		this.temporadases = temporadases;
	}

}
